# Generated by Django 4.1.6 on 2023-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("gerente", "Gerente"),
                    ("atendente", "Atendente"),
                    ("helper", "Helper"),
                ],
                max_length=100,
                verbose_name="Cargo:",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="payment",
            field=models.CharField(
                choices=[
                    ("D", "Dinheiro"),
                    ("C", "Cartão de Crédito"),
                    ("D", "Débito"),
                    ("P", "Pix"),
                ],
                max_length=100,
                verbose_name="Metodo de Pagamento:",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("P", "Pendente"), ("C", "Cancelado"), ("R", "Realizado")],
                max_length=100,
                verbose_name="Situação:",
            ),
        ),
    ]
