# Generated by Django 4.1.6 on 2023-02-18 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agendamento", "0002_alter_employee_options_alter_employee_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="payment",
            field=models.CharField(
                choices=[
                    ("debito", "Dinheiro"),
                    ("credito", "Crédito"),
                    ("debito", "Débito"),
                    ("pix", "Pix"),
                ],
                max_length=100,
                verbose_name="Metodo de Pagamento:",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("cancelado", "Cancelado"),
                    ("realizado", "Realizado"),
                ],
                max_length=100,
                verbose_name="Situação:",
            ),
        ),
    ]
