# Generated by Django 4.1.6 on 2023-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamento", "0003_remove_employee_name_employee_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
