# Generated by Django 4.1.6 on 2023-02-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agendamento", "0004_employee_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="employee",
        ),
        migrations.AddField(
            model_name="schedule",
            name="attendant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendente",
                to="agendamento.employee",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="helper",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ajudante",
                to="agendamento.employee",
            ),
        ),
    ]
