# Generated by Django 4.1.6 on 2023-02-18 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "agendamento",
            "0007_remove_schedule_attendant_alter_employee_position_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="service",
        ),
    ]
