# Generated by Django 4.1.6 on 2023-02-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agendamento", "0010_remove_attendant_schedule_attendant_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funcionario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="payment",
            field=models.CharField(
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("credito", "Crédito"),
                    ("debito", "Débito"),
                    ("pix", "Pix"),
                ],
                max_length=100,
                verbose_name="Metodo de Pagamento:",
            ),
        ),
    ]
