# Generated by Django 4.1.6 on 2023-02-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agendamento", "0011_alter_employee_user_alter_schedule_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="helper",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ajudante",
                to="agendamento.employee",
            ),
        ),
    ]
